import type { IconType } from "react-icons";
import { FaAws, FaCode, FaTerminal } from "react-icons/fa";

import {
  FaDatabase,
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaJava,
  FaLinkedin,
  FaPinterest,
  FaReddit,
  FaTelegram,
  FaThreads,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from "react-icons/fa6";

import {
  HiArrowDown,
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";

import {
  SiAnaconda,
  SiBootstrap,
  SiC,
  SiClaude,
  SiCss,
  SiCursor,
  SiDocker,
  SiFigma,
  SiFlask,
  SiGooglegemini,
  SiGsap,
  SiHtml5,
  SiHuggingface,
  SiJavascript,
  SiJest,
  SiJupyter,
  SiMysql,
  SiNextdotjs,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiSupabase,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

import { VscVscode } from "react-icons/vsc";

export const iconLibrary: Record<string, IconType> = {
  arrowDown: HiArrowDown,
  arrowRight: HiArrowRight,
  arrowUpRight: HiArrowUpRight,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  aws: FaAws,
  bash: FaTerminal,
  book: PiBookBookmarkDuotone,
  bootstrap: SiBootstrap,
  c: SiC,
  calendar: HiCalendarDays,
  claude: SiClaude,
  code: FaCode,
  conda: SiAnaconda,
  css: SiCss,
  cursor: SiCursor,
  database: FaDatabase,
  discord: FaDiscord,
  docker: SiDocker,
  document: HiOutlineDocument,
  email: HiEnvelope,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  facebook: FaFacebook,
  figma: SiFigma,
  flask: SiFlask,
  gallery: PiImageDuotone,
  gemini: SiGooglegemini,
  git: FaGithub,
  github: FaGithub,
  globe: HiOutlineGlobeAsiaAustralia,
  grid: PiGridFourDuotone,
  gsap: SiGsap,
  html: SiHtml5,
  home: PiHouseDuotone,
  huggingface: SiHuggingface,
  instagram: FaInstagram,
  java: FaJava,
  javascript: SiJavascript,
  jest: SiJest,
  jupyter: SiJupyter,
  linkedin: FaLinkedin,
  nextjs: SiNextdotjs,
  openLink: HiOutlineLink,
  person: PiUserCircleDuotone,
  pinterest: FaPinterest,
  postgresql: SiPostgresql,
  python: SiPython,
  pytorch: SiPytorch,
  r: SiR,
  react: SiReact,
  reddit: FaReddit,
  rocket: HiOutlineRocketLaunch,
  sql: SiMysql,
  supabase: SiSupabase,
  tailwind: SiTailwindcss,
  telegram: FaTelegram,
  terraform: SiTerraform,
  threads: FaThreads,
  twitter: FaXTwitter,
  typescript: SiTypescript,
  vercel: SiVercel,
  vscode: VscVscode,
  whatsapp: FaWhatsapp,
  x: FaX,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
