import { IconType } from "react-icons";
import { FaCode } from "react-icons/fa";
import { VscVscode } from "react-icons/vsc";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiArrowDown,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiTypescript,
  SiNextdotjs,
  SiCss3,
  SiHtml5,
  SiBootstrap,
  SiPython,
  SiR,
  SiC,
  SiFigma,
  SiSupabase,
  SiMysql,
  SiPostgresql,
  SiDocker,
  SiFlask,
  SiPytorch,
  SiReact,
  SiJupyter,
  SiAnaconda,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaJava, 
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  arrowDown: HiArrowDown,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  code: FaCode,
  vscode: VscVscode,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  nextjs: SiNextdotjs,
  css: SiCss3,
  html: SiHtml5,
  bootstrap: SiBootstrap,
  python: SiPython,
  r: SiR,
  java: FaJava,
  c: SiC,
  figma: SiFigma,
  supabase: SiSupabase,
  sql: SiMysql,
  postgresql: SiPostgresql,
  docker: SiDocker,
  flask: SiFlask,
  pytorch: SiPytorch,
  react: SiReact,
  jupyter: SiJupyter,
  conda: SiAnaconda,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
